# version属性在新版本Docker Compose中已废弃，移除以避免警告

services:
  # PostgreSQL 数据库服务
  postgres:
    image: postgres:15-alpine
    container_name: wuhr-ai-ops-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: wuhr_ai_ops
      POSTGRES_USER: wuhr_admin
      POSTGRES_PASSWORD: wuhr_secure_password_2024
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - wuhr-network

  # Redis 缓存服务（为未来功能准备）
  redis:
    image: redis:7-alpine
    container_name: wuhr-ai-ops-redis
    restart: unless-stopped
    command: redis-server --appendonly yes --requirepass redis_password_2024
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - wuhr-network

  # Wuhr AI Ops 主应用服务
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wuhr-ai-ops-app
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=wuhr_ai_ops
      - DB_USER=wuhr_admin
      - DB_PASSWORD=wuhr_secure_password_2024
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=redis_password_2024
      - DATABASE_URL=postgresql://wuhr_admin:wuhr_secure_password_2024@postgres:5432/wuhr_ai_ops?sslmode=disable&connection_limit=10&pool_timeout=20&connect_timeout=10
      - DIRECT_URL=postgresql://wuhr_admin:wuhr_secure_password_2024@postgres:5432/wuhr_ai_ops?sslmode=disable&connection_limit=5&pool_timeout=20&connect_timeout=10
      - JWT_SECRET=wuhr_ai_ops_jwt_secret_2024_production_change_this_in_production
      - ENCRYPTION_KEY=a1b2c3d4e5f6789012345678901234567890abcdef1234567890abcdef123456
      - NEXT_TELEMETRY_DISABLED=1
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
      - ./deployments:/app/deployments
      - app_logs:/app/logs
    networks:
      - wuhr-network
    depends_on:
      - postgres
      - redis
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        compress: "true"

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  app_logs:
    driver: local

networks:
  wuhr-network:
    driver: bridge