'use client'

import React,{useCallback,useEffect,useState}from'react'
import{Alert,Button,Card,Descriptions,Drawer,Form,Input,Modal,Radio,Select,Space,Table,Tag,Timeline,Typography,message}from'antd'
import{CheckOutlined,CloseOutlined,PlayCircleOutlined,PlusOutlined}from'@ant-design/icons'
import MainLayout from'../../components/layout/MainLayout'
import NetworkPageHeader from'../../components/network/NetworkPageHeader'
import{usePermissions}from'../../hooks/usePermissions'
import type{NetworkChange,NetworkDevice,NetworkGroup}from'../../types/network'
import{networkRequest,postNetwork}from'../../utils/networkClient'

const riskColor:Record<string,string>={low:'green',medium:'blue',high:'orange',critical:'red'};const statusColor:Record<string,string>={pending:'gold',approved:'blue',running:'processing',succeeded:'green',partial:'orange',failed:'red',rejected:'default'}
export default function NetworkChangesPage(){const{canAccessNetwork}=usePermissions();const canWrite=canAccessNetwork('write');const[changes,setChanges]=useState<NetworkChange[]>([]);const[devices,setDevices]=useState<NetworkDevice[]>([]);const[groups,setGroups]=useState<NetworkGroup[]>([]);const[loading,setLoading]=useState(false);const[action,setAction]=useState<string>();const[open,setOpen]=useState(false);const[detail,setDetail]=useState<NetworkChange>();const[form]=Form.useForm();const mode=Form.useWatch('mode',form)||'structured';const targetMode=Form.useWatch('targetMode',form)||'devices'
const load=useCallback(async()=>{setLoading(true);try{const[c,d,g]=await Promise.all([networkRequest<NetworkChange[]>('changes'),networkRequest<NetworkDevice[]>('devices'),networkRequest<NetworkGroup[]>('groups')]);setChanges(c??[]);setDevices(d??[]);setGroups(g??[])}catch(e:any){message.error(e.message)}finally{setLoading(false)}},[]);useEffect(()=>{load()},[load])
const create=async()=>{try{const v=await form.validateFields();const body:any={title:v.title,intent:v.intent,deviceIds:targetMode==='devices'?v.deviceIds:[],groupId:targetMode==='group'?v.groupId:'',parameters:{interface:v.interface,description:v.description}};if(v.mode==='raw')body.commands=String(v.commands).split('\n').map((x:string)=>x.trim()).filter(Boolean);else body.operation=v.operation;const result=await postNetwork<NetworkChange>('changes',body);message.success(result.requiresApproval?'计划已创建，等待人工审批':'只读计划已创建，可直接执行');setOpen(false);form.resetFields();setDetail(result);load()}catch(e:any){if(!e?.errorFields)message.error(e.message)}}
const doAction=async(c:NetworkChange,type:'approve'|'reject'|'execute')=>{setAction(`${c.id}:${type}`);try{const result=await postNetwork<NetworkChange>(`changes/${c.id}/${type}`,type==='execute'?{}:{reason:`在网络变更页面人工${type==='approve'?'批准':'拒绝'}`});message.success(type==='execute'?result.summary:(type==='approve'?'变更已批准':'变更已拒绝'));setDetail(result);load()}catch(e:any){message.error(e.message)}finally{setAction(undefined)}}
return <MainLayout><div className="p-6"><NetworkPageHeader title="变更管理" description="结构化意图按厂商生成命令，先固化计划，再审批、快照、灰度执行和验证。" onRefresh={load} loading={loading} action={canWrite?<Button type="primary" icon={<PlusOutlined/>} onClick={()=>{form.setFieldsValue({mode:'structured',targetMode:'devices',operation:'inspect_version'});setOpen(true)}}>创建计划</Button>:null}/><Alert className="mb-4" type="warning" showIcon message="模型不能直接执行" description="所有非只读命令都会进入待审批状态；生产、防火墙和多设备计划由确定性规则提升风险，模型不能自行降级。"/>
<Card><Table rowKey="id" loading={loading} dataSource={changes} scroll={{x:1050}} columns={[{title:'变更标题',dataIndex:'title',width:230,render:(v:string,r:NetworkChange)=><Button type="link" onClick={()=>setDetail(r)}>{v||r.intent}</Button>},{title:'风险',dataIndex:'riskLevel',render:(v:string)=><Tag color={riskColor[v]}>{v.toUpperCase()}</Tag>},{title:'目标数量',render:(_:unknown,r:NetworkChange)=>r.targets.length},{title:'状态',dataIndex:'status',render:(v:string)=><Tag color={statusColor[v]}>{v}</Tag>},{title:'申请人',dataIndex:'requestedBy'},{title:'申请时间',dataIndex:'createdAt',render:(v:string)=>new Date(v).toLocaleString()},{title:'执行摘要',dataIndex:'summary',ellipsis:true},{title:'操作',fixed:'right',width:240,render:(_:unknown,r:NetworkChange)=><Space>{r.status==='pending'&&<><Button type="primary" size="small" icon={<CheckOutlined/>} loading={action===`${r.id}:approve`} disabled={!canWrite} onClick={()=>doAction(r,'approve')}>批准</Button><Button size="small" danger icon={<CloseOutlined/>} loading={action===`${r.id}:reject`} disabled={!canWrite} onClick={()=>doAction(r,'reject')}>拒绝</Button></>}{r.status==='approved'&&<Button type="primary" danger={r.requiresApproval} size="small" icon={<PlayCircleOutlined/>} loading={action===`${r.id}:execute`} disabled={!canWrite} onClick={()=>Modal.confirm({title:'确认执行已固化的设备命令？',content:r.requiresApproval?'后端将先采集配置快照，并以第一台设备作为灰度目标。':'该计划全部为只读命令。',onOk:()=>doAction(r,'execute')})}>执行计划</Button>}</Space>}]}/></Card>
<Modal open={open} title="创建网络操作计划" width={760} onCancel={()=>setOpen(false)} onOk={create}><Form form={form} layout="vertical"><Form.Item name="title" label="计划标题" rules={[{required:true}]}><Input placeholder="生产核心交换机接口巡检"/></Form.Item><Form.Item name="intent" label="操作意图" rules={[{required:true}]}><Input.TextArea rows={2} placeholder="描述为什么要做、希望达到什么结果"/></Form.Item><Form.Item name="targetMode" label="目标选择"><Radio.Group options={[{value:'devices',label:'选择设备'},{value:'group',label:'选择设备组'}]}/></Form.Item>{targetMode==='devices'?<Form.Item name="deviceIds" label="目标设备" rules={[{required:true}]}><Select mode="multiple" showSearch optionFilterProp="label" options={devices.map(d=>({value:d.id,label:`${d.name} · ${d.vendor}/${d.platform} · ${d.managementIp}`}))}/></Form.Item>:<Form.Item name="groupId" label="设备分组" rules={[{required:true}]}><Select options={groups.map(g=>({value:g.id,label:g.name}))}/></Form.Item>}<Form.Item name="mode" label="计划方式"><Radio.Group options={[{value:'structured',label:'结构化操作（推荐）'},{value:'raw',label:'候选 CLI'}]}/></Form.Item>{mode==='structured'?<><Form.Item name="operation" label="标准操作" rules={[{required:true}]}><Select options={[{value:'inspect_version',label:'查询版本'},{value:'inspect_interfaces',label:'检查接口'},{value:'inspect_routing',label:'检查路由'},{value:'inspect_neighbors',label:'检查邻居'},{value:'backup_config',label:'备份配置'},{value:'set_interface_description',label:'修改接口描述'},{value:'shutdown_interface',label:'关闭接口'},{value:'no_shutdown_interface',label:'开启接口'}]}/></Form.Item><Form.Item noStyle shouldUpdate={(a,b)=>a.operation!==b.operation}>{({getFieldValue})=>['set_interface_description','shutdown_interface','no_shutdown_interface'].includes(getFieldValue('operation'))?<><Form.Item name="interface" label="接口名称" rules={[{required:true}]}><Input placeholder="GigabitEthernet1/0/1"/></Form.Item>{getFieldValue('operation')==='set_interface_description'&&<Form.Item name="description" label="接口描述" rules={[{required:true}]}><Input/></Form.Item>}</>:null}</Form.Item></>:<Form.Item name="commands" label="候选命令（每行一条）" rules={[{required:true}]} extra="未知命令按配置变更处理并强制审批；混合厂商应优先使用结构化操作。"><Input.TextArea rows={6} className="font-mono"/></Form.Item>}</Form></Modal>
<Drawer open={!!detail} onClose={()=>setDetail(undefined)} width={860} title={detail?.title||'变更详情'}>{detail&&<><Descriptions bordered size="small" column={2} items={[{key:'status',label:'状态',children:<Tag color={statusColor[detail.status]}>{detail.status}</Tag>},{key:'risk',label:'风险',children:<Tag color={riskColor[detail.riskLevel]}>{detail.riskLevel}</Tag>},{key:'requester',label:'申请人',children:detail.requestedBy},{key:'approver',label:'审批人',children:detail.approvedBy||'-'},{key:'intent',label:'意图',span:2,children:detail.intent},{key:'reason',label:'风险原因',span:2,children:detail.riskReasons?.join('；')||'只读操作'},{key:'summary',label:'执行摘要',span:2,children:detail.summary||'-'}]}/><Typography.Title level={4} className="mt-6">逐设备计划与结果</Typography.Title><Timeline items={detail.targets.map(t=>({color:t.status==='succeeded'?'green':t.status==='failed'?'red':'blue',children:<Card size="small" title={`${t.deviceName} · ${t.vendor}/${t.platform}`} extra={<Tag color={statusColor[t.status]}>{t.status}</Tag>}><Typography.Text strong>已固化命令</Typography.Text><pre className="mt-2 overflow-auto whitespace-pre-wrap rounded bg-slate-950 p-3 text-xs text-slate-100">{t.commands.join('\n')}</pre>{t.output&&<><Typography.Text strong>执行输出</Typography.Text><pre className="mt-2 max-h-72 overflow-auto whitespace-pre-wrap rounded bg-slate-950 p-3 text-xs text-slate-100">{t.output}</pre></>}{t.verificationOutput&&<><Typography.Text strong>验证输出</Typography.Text><pre className="mt-2 max-h-72 overflow-auto whitespace-pre-wrap rounded bg-slate-950 p-3 text-xs text-slate-100">{t.verificationOutput}</pre></>}{t.error&&<Alert type="error" showIcon message={t.error}/>}</Card>}))}/></>}</Drawer>
</div></MainLayout>}
