'use client'

import React,{useCallback,useEffect,useState}from'react'
import{Alert,Button,Card,Collapse,Form,Modal,Radio,Select,Space,Table,Tag,Typography,message}from'antd'
import{PlayCircleOutlined}from'@ant-design/icons'
import MainLayout from'../../components/layout/MainLayout'
import NetworkPageHeader from'../../components/network/NetworkPageHeader'
import{usePermissions}from'../../hooks/usePermissions'
import type{InspectionRun,NetworkDevice,NetworkGroup}from'../../types/network'
import{networkRequest,postNetwork}from'../../utils/networkClient'

export default function NetworkInspectionsPage(){const{canAccessNetwork}=usePermissions();const canWrite=canAccessNetwork('write');const[runs,setRuns]=useState<InspectionRun[]>([]);const[devices,setDevices]=useState<NetworkDevice[]>([]);const[groups,setGroups]=useState<NetworkGroup[]>([]);const[loading,setLoading]=useState(false);const[running,setRunning]=useState(false);const[open,setOpen]=useState(false);const[form]=Form.useForm();const targetMode=Form.useWatch('targetMode',form)||'devices';const load=useCallback(async()=>{setLoading(true);try{const[r,d,g]=await Promise.all([networkRequest<InspectionRun[]>('inspections'),networkRequest<NetworkDevice[]>('devices'),networkRequest<NetworkGroup[]>('groups')]);setRuns(r??[]);setDevices(d??[]);setGroups(g??[])}catch(e:any){message.error(e.message)}finally{setLoading(false)}},[]);useEffect(()=>{load()},[load]);const execute=async()=>{try{const v=await form.validateFields();setRunning(true);const run=await postNetwork<InspectionRun>('inspections',{name:v.name||`${v.profile}巡检`,profile:v.profile,deviceIds:targetMode==='devices'?v.deviceIds:[],groupId:targetMode==='group'?v.groupId:''});message.success(`巡检完成，共 ${run.results.length} 台设备`);setOpen(false);load()}catch(e:any){if(!e?.errorFields)message.error(e.message)}finally{setRunning(false)}}
return <MainLayout><div className="p-6"><NetworkPageHeader title="网络巡检" description="由程序按厂商选择只读命令并采集真实输出，一次巡检不会按设备重复请求模型。" onRefresh={load} loading={loading} action={canWrite?<Button type="primary" icon={<PlayCircleOutlined/>} onClick={()=>{form.setFieldsValue({targetMode:'devices',profile:'basic'});setOpen(true)}}>发起巡检</Button>:null}/><Alert className="mb-4" type="success" showIcon message="安全策略" description="巡检模板仅包含确定性的 show/display 命令；执行失败会自动生成持久化告警，不会尝试修改设备。"/>
<Card><Table rowKey="id" loading={loading} dataSource={runs} expandable={{expandedRowRender:(r:InspectionRun)=><Collapse items={r.results.map(x=>({key:x.deviceId,label:<Space>{x.deviceName}<Tag color={x.status==='succeeded'?'green':'red'}>{x.status}</Tag></Space>,children:<><Typography.Text strong>命令：{x.commands.join('；')}</Typography.Text>{x.error&&<Alert className="my-2" type="error" message={x.error}/>}<pre className="mt-2 max-h-96 overflow-auto whitespace-pre-wrap rounded bg-slate-950 p-3 text-xs text-slate-100">{x.output||'无输出'}</pre></>}))}/>}} columns={[{title:'巡检名称',dataIndex:'name'},{title:'模板',dataIndex:'profile',render:(v:string)=><Tag color="blue">{v}</Tag>},{title:'目标设备',render:(_:unknown,r:InspectionRun)=>r.deviceIds.length},{title:'成功/失败',render:(_:unknown,r:InspectionRun)=><Space><Tag color="green">{r.results.filter(x=>x.status==='succeeded').length}</Tag><Tag color="red">{r.results.filter(x=>x.status==='failed').length}</Tag></Space>},{title:'状态',dataIndex:'status',render:(v:string)=><Tag color={v==='succeeded'?'green':'orange'}>{v}</Tag>},{title:'发起人',dataIndex:'requestedBy'},{title:'完成时间',dataIndex:'completedAt',render:(v:string)=>v?new Date(v).toLocaleString():'执行中'}]}/></Card>
<Modal open={open} title="发起网络巡检" onCancel={()=>setOpen(false)} onOk={execute} confirmLoading={running} okText="开始真实巡检"><Form form={form} layout="vertical"><Form.Item name="name" label="巡检名称"><Select mode="tags" maxCount={1} placeholder="可输入自定义名称"/></Form.Item><Form.Item name="profile" label="巡检模板" rules={[{required:true}]}><Select options={[{value:'basic',label:'基础巡检（版本、接口）'},{value:'routing',label:'路由巡检（路由、邻居）'},{value:'full',label:'全面巡检'}]}/></Form.Item><Form.Item name="targetMode" label="目标方式"><Radio.Group options={[{value:'devices',label:'选择设备'},{value:'group',label:'选择设备组'}]}/></Form.Item>{targetMode==='devices'?<Form.Item name="deviceIds" label="目标设备" rules={[{required:true}]}><Select mode="multiple" options={devices.map(d=>({value:d.id,label:`${d.name} (${d.managementIp})`,disabled:!d.hasCredential}))}/></Form.Item>:<Form.Item name="groupId" label="设备组" rules={[{required:true}]}><Select options={groups.map(g=>({value:g.id,label:g.name}))}/></Form.Item>}</Form></Modal></div></MainLayout>}
