'use client'

import React,{useCallback,useEffect,useMemo,useState}from'react'
import{Alert,Button,Card,Col,Input,Modal,Row,Space,Table,Tag,Typography,message}from'antd'
import{CheckCircleOutlined}from'@ant-design/icons'
import MainLayout from'../../components/layout/MainLayout'
import NetworkPageHeader from'../../components/network/NetworkPageHeader'
import{usePermissions}from'../../hooks/usePermissions'
import type{NetworkAlert}from'../../types/network'
import{networkRequest,postNetwork}from'../../utils/networkClient'

const colors:Record<string,string>={info:'blue',warning:'orange',error:'red',critical:'magenta'}
export default function NetworkAlertsPage(){const{canAccessNetwork}=usePermissions();const canWrite=canAccessNetwork('write');const[alerts,setAlerts]=useState<NetworkAlert[]>([]);const[loading,setLoading]=useState(false);const[resolving,setResolving]=useState<NetworkAlert>();const[resolution,setResolution]=useState('');const load=useCallback(async()=>{setLoading(true);try{setAlerts((await networkRequest<NetworkAlert[]>('alerts'))??[])}catch(e:any){message.error(e.message)}finally{setLoading(false)}},[]);useEffect(()=>{load()},[load]);const stats=useMemo(()=>({open:alerts.filter(a=>!a.resolved).length,critical:alerts.filter(a=>!a.resolved&&a.level==='critical').length,resolved:alerts.filter(a=>a.resolved).length}),[alerts]);const resolve=async()=>{if(!resolving)return;if(!resolution.trim()){message.warning('请填写真实处理结果');return}try{await postNetwork(`alerts/${resolving.id}/resolve`,{resolution});message.success('告警已关闭并记录处理结果');setResolving(undefined);setResolution('');load()}catch(e:any){message.error(e.message)}}
return <MainLayout><div className="p-6"><NetworkPageHeader title="网络告警" description="巡检和变更失败产生真实持久化告警；关闭告警必须填写处理结果。" onRefresh={load} loading={loading}/><Alert className="mb-4" type="info" showIcon message="告警来源" description="当前已接入设备连接、巡检和变更执行链；gNMI/SNMP 实时指标只有在真实设备协议验证完成后才会启用。"/><Row gutter={[16,16]} className="mb-4"><Col xs={24} md={8}><Card><Typography.Text type="secondary">未处理</Typography.Text><Typography.Title level={3}>{stats.open}</Typography.Title></Card></Col><Col xs={24} md={8}><Card><Typography.Text type="secondary">严重告警</Typography.Text><Typography.Title level={3} type="danger">{stats.critical}</Typography.Title></Card></Col><Col xs={24} md={8}><Card><Typography.Text type="secondary">已关闭</Typography.Text><Typography.Title level={3}>{stats.resolved}</Typography.Title></Card></Col></Row><Card><Table rowKey="id" loading={loading} dataSource={alerts} columns={[{title:'级别',dataIndex:'level',render:(v:string)=><Tag color={colors[v]}>{v}</Tag>},{title:'设备',dataIndex:'deviceName',render:(v:string)=>v||'系统级'},{title:'类别',dataIndex:'category'},{title:'告警标题',dataIndex:'title'},{title:'详情',dataIndex:'message',ellipsis:true},{title:'状态',dataIndex:'resolved',render:(v:boolean)=><Tag color={v?'green':'red'}>{v?'已关闭':'待处理'}</Tag>},{title:'发生时间',dataIndex:'createdAt',render:(v:string)=>new Date(v).toLocaleString()},{title:'处理结果',dataIndex:'resolution',ellipsis:true},{title:'操作',render:(_:unknown,r:NetworkAlert)=>!r.resolved?<Button size="small" type="primary" icon={<CheckCircleOutlined/>} disabled={!canWrite} onClick={()=>setResolving(r)}>处理告警</Button>:<Space><Typography.Text type="secondary">{r.resolvedBy}</Typography.Text></Space>}]}/></Card><Modal open={!!resolving} title="处理网络告警" onCancel={()=>setResolving(undefined)} onOk={resolve} okText="确认关闭"><Typography.Paragraph>{resolving?.title}</Typography.Paragraph><Input.TextArea rows={4} value={resolution} onChange={e=>setResolution(e.target.value)} placeholder="填写排查过程、处理动作和验证结果；不能为空。"/></Modal></div></MainLayout>}
