'use client'

import React,{useCallback,useEffect,useMemo,useState}from'react'
import{Button,Card,Col,Drawer,Empty,Form,Modal,Row,Select,Space,Table,Tag,Typography,message}from'antd'
import{CloudDownloadOutlined,DiffOutlined}from'@ant-design/icons'
import MainLayout from'../../components/layout/MainLayout'
import NetworkPageHeader from'../../components/network/NetworkPageHeader'
import{usePermissions}from'../../hooks/usePermissions'
import type{ConfigSnapshot,NetworkDevice}from'../../types/network'
import{networkRequest,postNetwork}from'../../utils/networkClient'

function lineDiff(a:string,b:string){const left=new Set(a.split('\n'));const right=new Set(b.split('\n'));return{removed:Array.from(left).filter(x=>!right.has(x)),added:Array.from(right).filter(x=>!left.has(x))}}

export default function NetworkConfigsPage(){
 const{canAccessNetwork}=usePermissions();const canWrite=canAccessNetwork('write');const[devices,setDevices]=useState<NetworkDevice[]>([]);const[snapshots,setSnapshots]=useState<ConfigSnapshot[]>([]);const[loading,setLoading]=useState(false);const[capturing,setCapturing]=useState(false);const[open,setOpen]=useState(false);const[detail,setDetail]=useState<ConfigSnapshot>();const[compare,setCompare]=useState<string[]>([]);const[form]=Form.useForm()
 const load=useCallback(async()=>{setLoading(true);try{const[d,s]=await Promise.all([networkRequest<NetworkDevice[]>('devices'),networkRequest<ConfigSnapshot[]>('snapshots')]);setDevices(d??[]);setSnapshots(s??[])}catch(e:any){message.error(e.message)}finally{setLoading(false)}},[]);useEffect(()=>{load()},[load])
 const capture=async()=>{try{const v=await form.validateFields();setCapturing(true);await postNetwork(`devices/${v.deviceId}/capture-config`,{reason:v.reason||'人工配置备份'});message.success('已从设备采集真实运行配置');setOpen(false);load()}catch(e:any){if(!e?.errorFields)message.error(e.message)}finally{setCapturing(false)}}
 const selected=compare.map(id=>snapshots.find(s=>s.id===id)).filter(Boolean)as ConfigSnapshot[];const diff=useMemo(()=>selected.length===2?lineDiff(selected[0].content||'',selected[1].content||''):null,[compare,snapshots])
 return <MainLayout><div className="p-6"><NetworkPageHeader title="配置中心" description="保存真实 running configuration 的版本、哈希和采集人；支持版本内容与差异对比。" onRefresh={load} loading={loading} action={canWrite?<Button type="primary" icon={<CloudDownloadOutlined/>} onClick={()=>setOpen(true)}>采集配置</Button>:null}/>
 <Row gutter={[16,16]} className="mb-4"><Col xs={24} md={8}><Card><Typography.Text type="secondary">配置版本</Typography.Text><Typography.Title level={3}>{snapshots.length}</Typography.Title></Card></Col><Col xs={24} md={8}><Card><Typography.Text type="secondary">已备份设备</Typography.Text><Typography.Title level={3}>{new Set(snapshots.map(s=>s.deviceId)).size}</Typography.Title></Card></Col><Col xs={24} md={8}><Card><Typography.Text type="secondary">待备份设备</Typography.Text><Typography.Title level={3}>{devices.filter(d=>!snapshots.some(s=>s.deviceId===d.id)).length}</Typography.Title></Card></Col></Row>
 <Card className="mb-4" title={<Space><DiffOutlined/>版本对比</Space>}><Select mode="multiple" maxCount={2} className="w-full" value={compare} onChange={setCompare} placeholder="选择同一设备的两个配置版本" options={snapshots.map(s=>({value:s.id,label:`${s.deviceName} v${s.version} · ${new Date(s.createdAt).toLocaleString()}`}))}/>{diff&&<Row gutter={16} className="mt-4"><Col span={12}><Typography.Text type="danger">删除 {diff.removed.length} 行</Typography.Text><pre className="mt-2 max-h-64 overflow-auto whitespace-pre-wrap rounded bg-red-50 p-3 text-xs text-red-800 dark:bg-red-950 dark:text-red-100">{diff.removed.join('\n')||'无'}</pre></Col><Col span={12}><Typography.Text type="success">新增 {diff.added.length} 行</Typography.Text><pre className="mt-2 max-h-64 overflow-auto whitespace-pre-wrap rounded bg-green-50 p-3 text-xs text-green-800 dark:bg-green-950 dark:text-green-100">{diff.added.join('\n')||'无'}</pre></Col></Row>}</Card>
 <Card><Table rowKey="id" loading={loading} dataSource={snapshots} columns={[{title:'设备',dataIndex:'deviceName'},{title:'版本',dataIndex:'version',render:(v:number)=><Tag color="blue">v{v}</Tag>},{title:'来源',dataIndex:'source'},{title:'内容哈希',dataIndex:'contentHash',ellipsis:true,render:(v:string)=><Typography.Text code copyable>{v.slice(0,16)}…</Typography.Text>},{title:'采集原因',dataIndex:'reason'},{title:'采集人',dataIndex:'capturedBy'},{title:'时间',dataIndex:'createdAt',render:(v:string)=>new Date(v).toLocaleString()},{title:'操作',render:(_:unknown,r:ConfigSnapshot)=><Button size="small" onClick={()=>setDetail(r)}>查看配置</Button>}]}/></Card>
 <Modal open={open} title="采集运行配置" onCancel={()=>setOpen(false)} onOk={capture} confirmLoading={capturing}><Form form={form} layout="vertical"><Form.Item name="deviceId" label="目标设备" rules={[{required:true}]}><Select showSearch optionFilterProp="label" options={devices.map(d=>({value:d.id,label:`${d.name} (${d.managementIp})`,disabled:!d.hasCredential}))}/></Form.Item><Form.Item name="reason" label="采集原因"><Select options={[{value:'人工配置备份',label:'人工配置备份'},{value:'变更前基线',label:'变更前基线'},{value:'合规审计',label:'合规审计'}]}/></Form.Item></Form></Modal>
 <Drawer width={820} open={!!detail} onClose={()=>setDetail(undefined)} title={detail?`${detail.deviceName} · v${detail.version}`:'配置内容'}>{detail?.content?<pre className="min-h-96 overflow-auto whitespace-pre-wrap rounded bg-slate-950 p-4 text-xs text-slate-100">{detail.content}</pre>:<Empty description="无配置内容"/>}</Drawer>
 </div></MainLayout>
}
