'use client'
import React, { useEffect, useState } from 'react'
import { Alert, Button, Card, Form, Input, Modal, Popconfirm, Select, Space, Table, Tag, Typography, message } from 'antd'
import { DeleteOutlined, PlusOutlined, ReloadOutlined, ThunderboltOutlined } from '@ant-design/icons'
import MainLayout from '../components/layout/MainLayout'
import { usePermissions } from '../hooks/usePermissions'
const { Title, Paragraph, Text } = Typography
type Cluster = { id: string; name: string; contextName: string; defaultNamespace: string; environment?: string; status: string; kubernetesVersion?: string; lastVerifiedAt?: string; lastError?: string; server?: { name: string; ip: string } }
export default function ClustersPage() {
  const { canAccessServers } = usePermissions(); const canWrite = canAccessServers('write'); const [items,setItems]=useState<Cluster[]>([]); const [servers,setServers]=useState<any[]>([]); const [loading,setLoading]=useState(true); const [open,setOpen]=useState(false); const [form]=Form.useForm()
  const load=async()=>{setLoading(true);try{const [a,b]=await Promise.all([fetch('/api/k8s/clusters'),fetch('/api/servers')]);const [x,y]=await Promise.all([a.json(),b.json()]);if(!a.ok)throw new Error(x.error);setItems(x.data||[]);setServers(y.data?.servers||y.data||y.servers||[])}catch(e){message.error(e instanceof Error?e.message:'加载失败')}finally{setLoading(false)}};useEffect(()=>{load()},[])
  const create=async()=>{try{const values=await form.validateFields();const r=await fetch('/api/k8s/clusters',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(values)});const b=await r.json();if(!r.ok)throw new Error(b.error);message.success('集群已登记，请执行真实验证');setOpen(false);form.resetFields();await load()}catch(e){if(e instanceof Error)message.error(e.message)}}
  const act=async(id:string,type:'test'|'delete')=>{try{const r=await fetch(`/api/k8s/clusters/${id}${type==='test'?'/test':''}`,{method:type==='test'?'POST':'DELETE'});const b=await r.json();if(!r.ok)throw new Error(b.error);message.success(type==='test'?`验证成功：${b.data?.version||'版本已读取'}`:'集群已移除');await load()}catch(e){message.error(e instanceof Error?e.message:'操作失败')}}
  const columns=[{title:'集群名称',dataIndex:'name',render:(v:string,c:Cluster)=><div><Text strong>{v}</Text><div><Text type="secondary">{c.environment||'未设置环境'}</Text></div></div>},{title:'Context',dataIndex:'contextName',render:(v:string)=><code>{v}</code>},{title:'默认命名空间',dataIndex:'defaultNamespace'},{title:'Agent 主机',render:(_:unknown,c:Cluster)=>c.server?`${c.server.name} · ${c.server.ip}`:'主机缺失'},{title:'状态',dataIndex:'status',render:(v:string,c:Cluster)=><div><Tag color={v==='online'?'green':v==='error'?'red':'default'}>{v}</Tag><Text type="secondary">{c.kubernetesVersion||''}</Text></div>},{title:'操作',render:(_:unknown,c:Cluster)=><Space><Button size="small" type="primary" icon={<ThunderboltOutlined/>} disabled={!canWrite} onClick={()=>act(c.id,'test')}>验证</Button><Popconfirm title="确认移除集群目录？不会删除真实集群" onConfirm={()=>act(c.id,'delete')}><Button size="small" danger icon={<DeleteOutlined/>} disabled={!canWrite}/></Popconfirm></Space>}]
  return <MainLayout><div className="space-y-4"><div className="flex justify-between gap-3"><div><Title level={2} style={{margin:0}}>集群管理</Title><Paragraph type="secondary">将 Kubernetes Context 映射到实际运行 Agent 的主机，AI 选择集群后仍通过远端 2081 后端执行。</Paragraph></div><Space><Button icon={<ReloadOutlined/>} onClick={load}>刷新</Button><Button type="primary" icon={<PlusOutlined/>} disabled={!canWrite} onClick={()=>setOpen(true)}>登记集群</Button></Space></div><Alert showIcon type="info" message="凭据边界" description="平台只保存 Context 名称和 Agent 主机映射；kubeconfig 始终留在远端主机，不会发送到浏览器或数据库。"/><Card><Table rowKey="id" columns={columns} dataSource={items} loading={loading} scroll={{x:900}}/></Card></div><Modal title="登记 Kubernetes 集群" open={open} onCancel={()=>setOpen(false)} onOk={create}><Form form={form} layout="vertical" initialValues={{defaultNamespace:'default',tags:[]}}><Form.Item name="name" label="集群名称" rules={[{required:true,min:2}]}><Input/></Form.Item><Form.Item name="serverId" label="Agent 主机" rules={[{required:true}]}><Select options={servers.map(s=>({value:s.id,label:`${s.name} · ${s.ip}`}))}/></Form.Item><Form.Item name="contextName" label="Kubeconfig Context" rules={[{required:true}]}><Input placeholder="prod-cluster"/></Form.Item><Form.Item name="defaultNamespace" label="默认命名空间" rules={[{required:true}]}><Input/></Form.Item><Form.Item name="environment" label="环境"><Input placeholder="prod / staging"/></Form.Item><Form.Item name="description" label="说明"><Input.TextArea rows={2}/></Form.Item><Form.Item name="tags" label="标签"><Select mode="tags"/></Form.Item></Form></Modal></MainLayout>
}
