'use client'

import React,{useCallback,useEffect,useState}from'react'
import{Alert,Button,Card,Form,Input,Modal,Popconfirm,Select,Space,Table,Tag,Typography,message}from'antd'
import{ApartmentOutlined,DeleteOutlined,PlusOutlined}from'@ant-design/icons'
import MainLayout from'../../components/layout/MainLayout'
import NetworkPageHeader from'../../components/network/NetworkPageHeader'
import{usePermissions}from'../../hooks/usePermissions'
import type{NetworkDevice,TopologyLink}from'../../types/network'
import{deleteNetwork,networkRequest,postNetwork}from'../../utils/networkClient'

export default function NetworkTopologyPage(){const{canAccessNetwork}=usePermissions();const canWrite=canAccessNetwork('write');const[devices,setDevices]=useState<NetworkDevice[]>([]);const[links,setLinks]=useState<TopologyLink[]>([]);const[loading,setLoading]=useState(false);const[open,setOpen]=useState(false);const[form]=Form.useForm();const load=useCallback(async()=>{setLoading(true);try{const[d,l]=await Promise.all([networkRequest<NetworkDevice[]>('devices'),networkRequest<TopologyLink[]>('topology')]);setDevices(d??[]);setLinks(l??[])}catch(e:any){message.error(e.message)}finally{setLoading(false)}},[]);useEffect(()=>{load()},[load]);const name=(id:string)=>devices.find(d=>d.id===id)?.name||id;const save=async()=>{try{await postNetwork('topology',await form.validateFields());message.success('拓扑链路已持久化');setOpen(false);form.resetFields();load()}catch(e:any){if(!e?.errorFields)message.error(e.message)}};const remove=async(id:string)=>{try{await deleteNetwork(`topology/${id}`);message.success('链路已删除');load()}catch(e:any){message.error(e.message)}}
return <MainLayout><div className="p-6"><NetworkPageHeader title="网络拓扑" description="记录设备端口间链路，为后续 AI 影响分析和变更路径判断提供真实关系数据。" onRefresh={load} loading={loading} action={canWrite?<Button type="primary" icon={<PlusOutlined/>} onClick={()=>setOpen(true)}>添加链路</Button>:null}/><Alert className="mb-4" type="warning" showIcon message="自动发现边界" description="当前支持人工确认链路持久化；LLDP/CDP 自动采集尚未经过你的真实设备验证，因此不会显示为已发现。"/>
<Card className="mb-4" title={<Space><ApartmentOutlined/>链路视图</Space>}>{links.length===0?<Typography.Text type="secondary">暂无链路，请添加设备间的真实端口连接。</Typography.Text>:<div className="flex flex-wrap gap-3">{links.map(l=><Card size="small" key={l.id} className="min-w-72"><div className="flex items-center justify-between gap-2"><div><strong>{name(l.sourceDeviceId)}</strong><div><Typography.Text type="secondary">{l.sourcePort}</Typography.Text></div></div><Tag color="blue">{l.protocol||'manual'} →</Tag><div className="text-right"><strong>{name(l.targetDeviceId)}</strong><div><Typography.Text type="secondary">{l.targetPort}</Typography.Text></div></div></div></Card>)}</div>}</Card>
<Card><Table rowKey="id" loading={loading} dataSource={links} columns={[{title:'源设备',render:(_:unknown,r:TopologyLink)=>name(r.sourceDeviceId)},{title:'源端口',dataIndex:'sourcePort'},{title:'目标设备',render:(_:unknown,r:TopologyLink)=>name(r.targetDeviceId)},{title:'目标端口',dataIndex:'targetPort'},{title:'发现方式',render:(_:unknown,r:TopologyLink)=><Tag color={r.discovered?'green':'default'}>{r.discovered?(r.protocol||'自动发现'):'人工确认'}</Tag>},{title:'状态',dataIndex:'status',render:(v:string)=><Tag color="green">{v}</Tag>},{title:'操作',render:(_:unknown,r:TopologyLink)=><Popconfirm title="删除这条链路？" onConfirm={()=>remove(r.id)}><Button danger size="small" icon={<DeleteOutlined/>} disabled={!canWrite}/></Popconfirm>}]}/></Card>
<Modal open={open} title="添加拓扑链路" onCancel={()=>setOpen(false)} onOk={save}><Form form={form} layout="vertical"><Form.Item name="sourceDeviceId" label="源设备" rules={[{required:true}]}><Select options={devices.map(d=>({value:d.id,label:d.name}))}/></Form.Item><Form.Item name="sourcePort" label="源端口" rules={[{required:true}]}><Input placeholder="GE1/0/1"/></Form.Item><Form.Item name="targetDeviceId" label="目标设备" rules={[{required:true}]}><Select options={devices.map(d=>({value:d.id,label:d.name}))}/></Form.Item><Form.Item name="targetPort" label="目标端口" rules={[{required:true}]}><Input placeholder="GE1/0/24"/></Form.Item><Form.Item name="protocol" label="确认协议"><Select options={[{value:'manual',label:'人工确认'},{value:'lldp',label:'LLDP'},{value:'cdp',label:'CDP'}]}/></Form.Item></Form></Modal></div></MainLayout>}
